name: Build and Push Docker Image

on:
  push:
    branches: [ "main", "develop" ] # 當 main 或 develop 分支有更新時觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        # 注意：這裡會自動將 Image 推送到你的 Docker Hub
        # 請確保下面的 your-dockerhub-user 改成你自己的帳號
        tags: ${{ secrets.joliej }}/weather-app:latest